[[redirects]]
from = "/sus/script.js"
to = "https://plausible.io/js/script.js"
status = 200

[[redirects]]
from = "/sus/event"
to = "https://plausible.io/api/event"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; child-src 'none'; img-src * blob: data:; media-src 'none'; connect-src *;"
